create or replace function public.depurnrfi_d_jsonb_hash(p jsonb) returns text language sql immutable as $$ select encode(digest(convert_to(coalesce(p,'null'::jsonb)::text,'UTF8'),'sha256'),'hex') $$;
create or replace function public.depurnrfi_d_text_hash(p text) returns text language sql immutable as $$ select encode(digest(convert_to(coalesce(p,''),'UTF8'),'sha256'),'hex') $$;

create or replace function public.depurnrfi_d_write_guard() returns trigger language plpgsql as $$ begin if coalesce(current_setting('depurnrfi_d.kernel_commit',true),'') <> 'on' then raise exception 'DEPURNRFI_D_DIRECT_WRITE_FORBIDDEN'; end if; if tg_op='DELETE' then return old; else return new; end if; end $$;

drop trigger if exists depurnrfi_d_runs_guard on public.depurnrfi_d_runs; create trigger depurnrfi_d_runs_guard before insert or update or delete on public.depurnrfi_d_runs for each row execute function public.depurnrfi_d_write_guard();
drop trigger if exists depurnrfi_d_reqstate_guard on public.depurnrfi_d_requirement_state; create trigger depurnrfi_d_reqstate_guard before insert or update or delete on public.depurnrfi_d_requirement_state for each row execute function public.depurnrfi_d_write_guard();
drop trigger if exists depurnrfi_d_receipts_guard on public.depurnrfi_d_phase_receipts; create trigger depurnrfi_d_receipts_guard before insert or update or delete on public.depurnrfi_d_phase_receipts for each row execute function public.depurnrfi_d_write_guard();
drop trigger if exists depurnrfi_d_artifacts_guard on public.depurnrfi_d_artifacts; create trigger depurnrfi_d_artifacts_guard before insert or update or delete on public.depurnrfi_d_artifacts for each row execute function public.depurnrfi_d_write_guard();
drop trigger if exists depurnrfi_d_reports_guard on public.depurnrfi_d_pre_dialogue_reports; create trigger depurnrfi_d_reports_guard before insert or update or delete on public.depurnrfi_d_pre_dialogue_reports for each row execute function public.depurnrfi_d_write_guard();
drop trigger if exists depurnrfi_d_turns_guard on public.depurnrfi_d_dialogue_turns; create trigger depurnrfi_d_turns_guard before insert or update or delete on public.depurnrfi_d_dialogue_turns for each row execute function public.depurnrfi_d_write_guard();
drop trigger if exists depurnrfi_d_closings_guard on public.depurnrfi_d_dialogue_closings; create trigger depurnrfi_d_closings_guard before insert or update or delete on public.depurnrfi_d_dialogue_closings for each row execute function public.depurnrfi_d_write_guard();
drop trigger if exists depurnrfi_d_events_guard on public.depurnrfi_d_events; create trigger depurnrfi_d_events_guard before insert or update or delete on public.depurnrfi_d_events for each row execute function public.depurnrfi_d_write_guard();

create or replace function public.depurnrfi_d_has_forbidden_key(p jsonb,p_keys text[]) returns boolean language plpgsql immutable as $$ declare k text; v jsonb; x jsonb; begin if p is null then return false; end if; if jsonb_typeof(p)='object' then for k,v in select key,value from jsonb_each(p) loop if lower(k)=any(p_keys) then return true; end if; if public.depurnrfi_d_has_forbidden_key(v,p_keys) then return true; end if; end loop; elsif jsonb_typeof(p)='array' then for x in select value from jsonb_array_elements(p) loop if public.depurnrfi_d_has_forbidden_key(x,p_keys) then return true; end if; end loop; end if; return false; end $$;

create or replace function public.depurnrfi_d_validate_phase_output(p_phase text,p_output jsonb) returns void language plpgsql immutable as $$ declare c integer; gate text; frozen text; begin if p_output is null or jsonb_typeof(p_output)<>'object' then raise exception 'DEPURNRFI_D_PHASE_OUTPUT_OBJECT_REQUIRED'; end if; if p_phase in ('D1','D2') and public.depurnrfi_d_has_forbidden_key(p_output,array['candidate','candidate_a','candidate_b','candidate_c','candidate_d','top_4','advances_to_deep_analysis','eliminated','final_nrfi','bet','probability','edge','fair_price','lock']) then raise exception 'DEPURNRFI_D_PRE_F10_SELECTION_AUTHORITY_VIOLATION phase=%',p_phase; end if; if p_phase in ('F10','F11') and public.depurnrfi_d_has_forbidden_key(p_output,array['final_nrfi','final_nrfi_bet','bet','bet_size','probability','fair_price','edge','lock','safe_game','guaranteed','rank_1_to_4']) then raise exception 'DEPURNRFI_D_BETTING_OR_FINAL_NRFI_AUTHORITY_FORBIDDEN phase=%',p_phase; end if; if p_phase='F10' then begin c=coalesce(nullif(p_output->>'ADVANCED_CANDIDATE_COUNT','')::integer,nullif(p_output->>'candidate_count','')::integer); exception when invalid_text_representation then raise exception 'DEPURNRFI_D_F10_CANDIDATE_COUNT_INVALID'; end; if c is null then raise exception 'DEPURNRFI_D_F10_CANDIDATE_COUNT_REQUIRED'; end if; if c<0 or c>4 then raise exception 'DEPURNRFI_D_F10_MAX_FOUR_VIOLATION count=%',c; end if; end if; if p_phase='F11' then begin c=coalesce(nullif(p_output->>'CANDIDATE_COUNT','')::integer,nullif(p_output->>'candidate_count','')::integer); exception when invalid_text_representation then raise exception 'DEPURNRFI_D_F11_CANDIDATE_COUNT_INVALID'; end; if c is null or c<0 or c>4 then raise exception 'DEPURNRFI_D_F11_MAX_FOUR_OR_COUNT_MISSING'; end if; gate=upper(coalesce(p_output->>'HANDOFF_COMPLETENESS_GATE',p_output->>'handoff_completeness_gate','')); if gate<>'PASS' then raise exception 'DEPURNRFI_D_F11_HANDOFF_COMPLETENESS_GATE_REQUIRED'; end if; frozen=lower(coalesce(p_output->>'PRE_DEEP_ANALYSIS_POSITION_FROZEN',p_output->>'pre_deep_analysis_position_frozen','')); if frozen not in ('yes','true','1') then raise exception 'DEPURNRFI_D_F11_PRE_DEEP_FREEZE_REQUIRED'; end if; end if; end $$;

create or replace function public.depurnrfi_d_append_event(p_run_id text,p_phase text,p_type text,p_state_version integer,p_payload jsonb) returns void language plpgsql security definer set search_path=public,extensions as $$ begin insert into public.depurnrfi_d_events(run_id,phase_code,event_type,state_version,payload,payload_hash) values(p_run_id,p_phase,p_type,p_state_version,coalesce(p_payload,'{}'::jsonb),public.depurnrfi_d_jsonb_hash(coalesce(p_payload,'{}'::jsonb))); end $$;
