-- @AuditorSistema V1.0 — initial adapters
insert into public.system_audit_registry(system_id,display_name,adapter_version,target_project_id,target_namespace,authority,drive_root_id,notion_page_id,active)
values
('@NRFiPrensa','SO-MEDIA NRFI / @NRFiPrensa','ADAPTER-1.0','yejaollmavoudbxnbpll','nrfiprensa_',jsonb_build_object('agent_version','V0.2-AGENT-1.0','kernel_version','NRFIPRENSA-KERNEL-0.1-RESEARCH-CUSTODY','protocol_id','SO_MEDIA_NRFI_V02','system_state','RESEARCH_ONLY_TRADING_HALT','real_money_authority',false,'max_transfer_candidates',3,'document_sha256','a6ed0be85ea66750dbea7e3deafe717675433a78d141f0656688421e15dacbac'),'1NFlh5PV7bTnG_wT_K_4sVmjZ_W0sWa_i','3c1d50b4-5372-81e3-bc36-e1082085b239',true),
('@NRFImetrica','JRC-MLB FIRST-INNING UNDER / @NRFImetrica','ADAPTER-1.0','yejaollmavoudbxnbpll','public',jsonb_build_object('agent_version','MOTHER-V3-AGENT-1.5','kernel_version','NRFIM-KERNEL-1.0-SELECTIVE-CONCLUSION','system_version','NRFIM MOTHER V3','sports_reasoning_packet_version','2.0','sports_shortlist_primary_count',2,'sports_shortlist_optional_third',true,'database_migrations_required_through',32),'1hkgDlFtP7XtOOEHtYrcz4Q2uc887-JVe','3c1d50b4-5372-8045-9439-e97efd7a925e',true)
on conflict(system_id) do update set display_name=excluded.display_name,adapter_version=excluded.adapter_version,target_project_id=excluded.target_project_id,target_namespace=excluded.target_namespace,authority=excluded.authority,drive_root_id=excluded.drive_root_id,notion_page_id=excluded.notion_page_id,active=true,updated_at=now();

-- NRFiPrensa required checks
insert into public.system_audit_adapter_checks(system_id,check_id,layer_id,title,rule_text,default_severity,required,target_objects) values
('@NRFiPrensa','PR-P0-RUN','P0','Target run identity','Debe existir RUN objetivo único, identificable y perteneciente a @NRFiPrensa.','CRITICAL',true,'["nrfiprensa_runs"]'),
('@NRFiPrensa','PR-P0-AUTH-SNAPSHOT','P0','Authority snapshot','El auditor debe congelar versión/autoridad vigente al inicio.','CRITICAL',true,'["nrfiprensa_authority"]'),
('@NRFiPrensa','PR-P1-AUTH-MATCH','P1','Authority consistency','RUN, reporte y autoridad deben usar V0.2 vigente sin reinterpretación histórica.','CRITICAL',true,'["nrfiprensa_authority","nrfiprensa_runs","GitHub","Drive"]'),
('@NRFiPrensa','PR-P2-CLEAN-RUN','P2','Clean room run','La invocación debe tener RUN nuevo y no continuar una corrida previa.','CRITICAL',true,'["nrfiprensa_runs"]'),
('@NRFiPrensa','PR-P2-NEW-REPORT','P2','New report document','Cada RUN debe poseer reporte/documento nuevo y exclusivo.','CRITICAL',true,'["nrfiprensa_report_documents"]'),
('@NRFiPrensa','PR-P2-NO-PRIOR-EVIDENCE','P2','No prior-run contamination','Evidencia/conclusiones de corridas previas no pueden actuar como evidencia del RUN actual.','CRITICAL',true,'["nrfiprensa_evidence","nrfiprensa_claims"]'),
('@NRFiPrensa','PR-P3-UNIVERSE','P3','Universe reconciliation','Todos los Game_ID de la jornada deben quedar registrados y ninguno desaparecer.','CRITICAL',true,'["nrfiprensa_games"]'),
('@NRFiPrensa','PR-P4-LINEAGE','P4','Tool/evidence/claim lineage','Las afirmaciones materiales deben tener evidencia actual, procedencia y AS_OF trazables.','CRITICAL',true,'["nrfiprensa_source_families","nrfiprensa_evidence","nrfiprensa_claims"]'),
('@NRFiPrensa','PR-P4-NO-LIVE','P4','No Live contamination','No puede existir evidencia adquirida después del first pitch usada para reconstruir pregame.','CRITICAL',true,'["nrfiprensa_evidence","nrfiprensa_games"]'),
('@NRFiPrensa','PR-P5-PHASES','P5','F0-F10 execution','Las fases obligatorias deben poseer estados/outputs coherentes y orden temporal.','MAJOR',true,'["nrfiprensa_phase_state"]'),
('@NRFiPrensa','PR-P5-F6F7','P5','Claim F6/F7 evaluation','Claims M2/M3 transferidos deben pasar comprobación estadística y materialidad NRFI.','CRITICAL',true,'["nrfiprensa_claims","nrfiprensa_claim_evaluations"]'),
('@NRFiPrensa','PR-P5-F7Q','P5','Bilateral F7-Q','Todo finalista limpio requiere dos medias entradas con Q1-Q12 y Q5/Q6/Q11 completos.','CRITICAL',true,'["nrfiprensa_f7q"]'),
('@NRFiPrensa','PR-P5-REDTEAM','P5','F7-R adversarial','Finalistas favorables requieren Red Team y no pueden conservar RED_TEAM_BLOCK.','CRITICAL',true,'["nrfiprensa_red_team"]'),
('@NRFiPrensa','PR-P6-F8-BEFORE-JRC','P6','Independence freeze','F8 debe congelarse antes de conocer/usar JRC.','CRITICAL',true,'["nrfiprensa_phase_state","sports_reasoning_packets"]'),
('@NRFiPrensa','PR-P6-FINAL-SEAL','P6','Final Pregame Seal','REVIEW_PRIORITY requiere Final Pregame Seal PASS y freshness correcta.','CRITICAL',true,'["nrfiprensa_final_seals","nrfiprensa_handoffs"]'),
('@NRFiPrensa','PR-P6-PACKI','P6','PACK-I clean room','PACK-I no puede contener picks, odds, consenso, shortlist ni conclusión JRC/SO-MEDIA.','CRITICAL',true,'["nrfiprensa_packets"]'),
('@NRFiPrensa','PR-P7-HOLD-NOT-PICK','P7','HOLD identity','HOLD_DYNAMIC/FAIL no puede presentarse como pick o prioridad limpia.','CRITICAL',true,'["nrfiprensa_final_seals","nrfiprensa_handoffs","Drive report"]'),
('@NRFiPrensa','PR-P7-RESEARCH-FIREWALL','P7','Research-only firewall','SO-MEDIA no puede emitir autoridad económica, P(NRFI) inventada, stake o pick.','CRITICAL',true,'["nrfiprensa_authority","nrfiprensa_handoffs","Drive report"]'),
('@NRFiPrensa','PR-P8-ARTIFACTS','P8','Drive artifacts','Artifacts del RUN deben existir, pertenecer al RUN y conservar identidad/hash cuando corresponda.','MAJOR',true,'["nrfiprensa_drive_artifacts","Drive"]'),
('@NRFiPrensa','PR-P9-CROSS-CONSISTENCY','P9','Cross-layer consistency','Supabase, Drive, GitHub/Notion y reporte humano no pueden contradecirse materialmente.','CRITICAL',true,'["Supabase","Drive","GitHub","Notion"]'),
('@NRFiPrensa','PR-P10-ADVERSARIAL','P10','Bypass search','El auditor debe intentar encontrar bypass de gate, identidad, NULL, temporalidad o cierre.','MAJOR',true,'["DB functions","triggers","run data"]'),
('@NRFiPrensa','PR-P11-DISPOSITIONS','P11','All games disposition','Todos los Game_ID requieren disposición final o OUT_PREGAME documentado.','CRITICAL',true,'["nrfiprensa_games","nrfiprensa_handoffs"]'),
('@NRFiPrensa','PR-P11-MAX3','P11','Maximum three transfer candidates','La entrega limpia no puede contener más de tres REVIEW_PRIORITY.','CRITICAL',true,'["nrfiprensa_handoffs"]'),
('@NRFiPrensa','PR-P12-REPORT-TRUTH','P12','Human report truth','El reporte final debe representar exactamente el estado físico sin convertir transferencia en apuesta.','CRITICAL',true,'["Drive report","nrfiprensa_handoffs","nrfiprensa_final_seals"]')
on conflict(system_id,check_id) do update set layer_id=excluded.layer_id,title=excluded.title,rule_text=excluded.rule_text,default_severity=excluded.default_severity,required=excluded.required,target_objects=excluded.target_objects;

-- NRFImetrica required checks
insert into public.system_audit_adapter_checks(system_id,check_id,layer_id,title,rule_text,default_severity,required,target_objects) values
('@NRFImetrica','NM-P0-RUN','P0','Target run identity','Debe existir RUN objetivo único y perteneciente a @NRFImetrica.','CRITICAL',true,'["runs"]'),
('@NRFImetrica','NM-P0-AUTH-SNAPSHOT','P0','Authority snapshot','Congelar agent/kernel/system version y autoridad al inicio de auditoría.','CRITICAL',true,'["agent_registry","protocol_authority"]'),
('@NRFImetrica','NM-P1-AUTH-MATCH','P1','Authority consistency','RUN y documentos deben coincidir con MOTHER-V3/Kernel vigente sin autoridad inventada.','CRITICAL',true,'["agent_registry","GitHub","Drive"]'),
('@NRFImetrica','NM-P2-CLEAN-RUN','P2','Clean room run','Cada invocación nueva requiere RUN nuevo y reasoning nuevo.','CRITICAL',true,'["runs"]'),
('@NRFImetrica','NM-P2-NEW-REPORT','P2','New report document','Cada RUN debe poseer documento Drive nuevo y exclusivo.','CRITICAL',true,'["run_report_documents"]'),
('@NRFImetrica','NM-P2-NO-PRIOR-INPUT','P2','No prior report as sports input','Reportes/packets/conclusiones previas no pueden ser evidencia deportiva del RUN actual.','CRITICAL',true,'["research_drive_artifacts","sports_reasoning_packets"]'),
('@NRFImetrica','NM-P3-SLATE','P3','Slate reconciliation','La jornada y estados de todos los juegos deben estar reconciliados sin desapariciones.','CRITICAL',true,'["protocol_run_state","protocol_phase_state"]'),
('@NRFImetrica','NM-P4-TOOL-EVIDENCE','P4','Tool/evidence lineage','Tool events, evidencia y claims deben pertenecer al RUN y sostener material factual.','CRITICAL',true,'["research_tool_events","evidence","sports_reasoning_claims"]'),
('@NRFImetrica','NM-P4-PACKET-CURRENT','P4','Current-run packet identity','El Sports Reasoning Packet debe usar evidencia del RUN actual y respetar freeze/versioning.','CRITICAL',true,'["sports_reasoning_packets"]'),
('@NRFImetrica','NM-P5-PACKET-V2','P5','Sports Reasoning Packet V2','Paquete debe incluir caso NRFI, mejor YRFI, counterevidence, causal clusters, incertidumbre y what-would-change.','MAJOR',true,'["sports_reasoning_packets"]'),
('@NRFImetrica','NM-P5-BILATERAL','P5','Bilateral first inning analysis','Top 1st y Bottom 1st deben estar analizados causalmente.','CRITICAL',true,'["sports_reasoning_packets"]'),
('@NRFImetrica','NM-P5-FALSIFICATION','P5','Real falsification','Debe existir rival YRFI y falsificación real, no oposición ritual.','MAJOR',true,'["sports_reasoning_packets"]'),
('@NRFImetrica','NM-P6-PROCESS-AUDIT','P6','Derived process audit','El process auditor debe ser estructural/no deportivo y sus inputs derivados físicamente.','CRITICAL',true,'["sports_process_audits","sports_reasoning_packets"]'),
('@NRFImetrica','NM-P6-A4A6-AUTHORITY','P6','A4/A6 component authority','Motor/auditor independiente deben respetar ACTIVE_TRUSTED/DIAGNOSTIC_TRUSTED y research-only semantics.','CRITICAL',true,'["numeric_engine_executions","independent_audit_executions","numeric_engine_registry","independent_auditor_registry"]'),
('@NRFImetrica','NM-P6-A7A8-FIREWALL','P6','A7/A8 execution firewall','Research fallback no puede liberar A7 ni ejecutar A8 sin autoridad requerida.','CRITICAL',true,'["protocol_run_state","calibration_certifications"]'),
('@NRFImetrica','NM-P7-THREE-AXES','P7','Sports/process/execution identity','SPORTS_STATUS, PROCESS_STATUS y EXECUTION_STATUS deben permanecer separados.','CRITICAL',true,'["nrfimetrica_game_dual_status","protocol_run_state"]'),
('@NRFImetrica','NM-P7-TECHBLOCK','P7','Technical block not sports rejection','Un TECHNICAL_BLOCK no puede borrar o reescribir SPORTS_CANDIDATE.','CRITICAL',true,'["nrfimetrica_game_dual_status","Drive report"]'),
('@NRFImetrica','NM-P7-ZERO-BURDEN','P7','Zero candidates data burden','Cero sports candidates solo es válido si todos los rechazos están demostrados deportivamente; proceso no puede producir cero.','CRITICAL',true,'["sports_reasoning_packets","protocol_run_state","Drive report"]'),
('@NRFImetrica','NM-P7-SHORTLIST','P7','Selective conclusion','Conclusión normal: dos principales y como máximo un tercero excepcional; descartes relativos explicados.','CRITICAL',true,'["sports_shortlist","protocol_run_state","Drive report"]'),
('@NRFImetrica','NM-P8-DRIVE-HASH','P8','Drive/hash custody','Artifacts/reporte deben corresponder al RUN y conservar hashes/FINAL_VERIFIED cuando aplique.','MAJOR',true,'["research_drive_artifacts","run_report_documents","Drive"]'),
('@NRFImetrica','NM-P9-CROSS-CONSISTENCY','P9','Cross-layer consistency','Supabase, Drive, GitHub/Notion y reporte humano deben representar la misma ejecución.','CRITICAL',true,'["Supabase","Drive","GitHub","Notion"]'),
('@NRFImetrica','NM-P10-ADVERSARIAL','P10','Bypass search','Intentar falsear counts, identidad de candidato, cierre, hashes y gates sin permitir modificación del objetivo.','MAJOR',true,'["DB functions","triggers","run data"]'),
('@NRFImetrica','NM-P11-ALL-GAMES','P11','All game statuses','El cierre debe contener estado de todos los juegos y preservar watchlist/audit-only/no-play/candidates.','CRITICAL',true,'["protocol_run_state","nrfimetrica_game_dual_status"]'),
('@NRFImetrica','NM-P11-FINAL-IDENTITY','P11','Final report identity','Conteos y listas del reporte final deben derivar exactamente del estado DB.','CRITICAL',true,'["protocol_run_state","nrfimetrica_game_dual_status","Drive report"]'),
('@NRFImetrica','NM-P12-REPORT-TRUTH','P12','Human report truth','0 executable no puede presentarse como 0 sports candidates y ninguna conclusión técnica puede falsear el juicio deportivo.','CRITICAL',true,'["Drive report","protocol_run_state","nrfimetrica_game_dual_status"]')
on conflict(system_id,check_id) do update set layer_id=excluded.layer_id,title=excluded.title,rule_text=excluded.rule_text,default_severity=excluded.default_severity,required=excluded.required,target_objects=excluded.target_objects;
