insert into public.system_audit_registry(system_id,display_name,adapter_version,target_project_id,target_namespace,authority,drive_root_id,notion_page_id,active)
values ('@DepuracionMLB','DEPURACIÓN MLB FULL GAME UNDER / @DepuracionMLB','ADAPTER-1.0','yejaollmavoudbxnbpll','dep_mlb_',jsonb_build_object('system_version','DEP-MLB-V0.3','agent_version','DEP-MLB-AGENT-1.2','kernel_version','DEP-MLB-KERNEL-0.4-AUTONOMOUS-REFACTOR','protocol_id','DEPURACION_MLB_V0_3_PROGRESSIVE','mother_document_id','1nod0j35fZeILy7fxUk5IPCT7_qn3f0sEFsxmLbDdfrA','mother_document_sha256','0e4b1382597930cc48b1f40a39d824a4f45208f505c462e9e623e31a0f8130d2','github_repository','geo2343/depuracion-mlb-kernel','execution_owner','AI_AGENT_ORCHESTRATOR','primary_candidates_max',4,'potential_candidates_max',2,'chat_standard','MLB_CHAT_REPORT_STANDARD_R1','handoff','DEPURATION_HANDOFF_PACKET','real_money_authority',false,'f9_comparative_coverage','ALL_ELIGIBLE_GAMES_PLUS_HORIZONTAL_AUDIT','controlled_e2e_run','TEST-DEP-AUTONOMOUS-E2E-V04','kernel_tests_pass','17/17','real_sports_execution_quality','NOT_YET_PERFORMED'),'1N8r-rn51Cj2kokFxIzasvhIlH6P1-x4i',null,true)
on conflict (system_id) do update set display_name=excluded.display_name,adapter_version=excluded.adapter_version,target_project_id=excluded.target_project_id,target_namespace=excluded.target_namespace,authority=excluded.authority,drive_root_id=excluded.drive_root_id,active=true,updated_at=now();

delete from public.system_audit_adapter_checks where system_id='@DepuracionMLB';
insert into public.system_audit_adapter_checks(system_id,check_id,layer_id,title,rule_text,default_severity,required,target_objects) values
('@DepuracionMLB','DEP-P0-01','P0','Target run resolved physically','Resolve exact dep_mlb_runs RUN_ID from Supabase; never choose by memory or narrative.','CRITICAL',true,'["dep_mlb_runs"]'),
('@DepuracionMLB','DEP-P0-02','P0','Current authority identity','Reconcile run authority against current DEP-MLB-V0.3 / AGENT-1.2 / KERNEL-0.4 or explicitly classify run historical.','CRITICAL',true,'["dep_mlb_runs","GitHub agent manifest"]'),
('@DepuracionMLB','DEP-P1-01','P1','Canonical constitution identity','Verify canonical Mother Drive ID, SHA and operational notice against current manifest.','CRITICAL',true,'["Drive mother","GitHub manifest"]'),
('@DepuracionMLB','DEP-P1-02','P1','Required connectors physically available','Supabase, Drive, GitHub and Web must be VERIFIED_AVAILABLE; Vercel is optional.','MAJOR',true,'["dep_mlb_connector_registry"]'),
('@DepuracionMLB','DEP-P1-03','P1','No betting authority','Agent output remains depuration/handoff research and cannot claim wager authority.','CRITICAL',true,'["manifest","handoffs","chat_reports"]'),
('@DepuracionMLB','DEP-P2-01','P2','Fresh invocation and run','Each invocation binds to a new invocation_id and fresh RUN_ID.','CRITICAL',true,'["dep_mlb_agent_invocations","dep_mlb_runs"]'),
('@DepuracionMLB','DEP-P2-02','P2','Exclusive Drive report before sports analysis','New Drive folder/report must exist and be read back through Drive connector before run creation and sports analysis.','CRITICAL',true,'["dep_mlb_invocation_drive_receipts","dep_mlb_invocation_connector_events","dep_mlb_runs"]'),
('@DepuracionMLB','DEP-P2-03','P2','No prior-run sports reuse','No prior-run evidence, reasoning, packets or candidates may seed audited run.','CRITICAL',true,'["dep_mlb_evidence","dep_mlb_game_packets","dep_mlb_handoffs"]'),
('@DepuracionMLB','DEP-P3-01','P3','Slate universe frozen','Audited run must have physical universe freeze/hash and all games represented.','CRITICAL',true,'["dep_mlb_runs","dep_mlb_games"]'),
('@DepuracionMLB','DEP-P3-02','P3','No silent game disappearance','Every eligible/excluded game retains explicit state/disposition.','CRITICAL',true,'["dep_mlb_games","dep_mlb_phase_state","dep_mlb_handoffs"]'),
('@DepuracionMLB','DEP-P4-01','P4','Fresh same-run Web research','Every material sports lookup is a fresh Web tool event after run start.','CRITICAL',true,'["dep_mlb_tool_events"]'),
('@DepuracionMLB','DEP-P4-02','P4','Sports evidence lineage complete','Evidence retains URL/origin/AS_OF/family/snapshot/response-hash lineage to same-run tool event.','CRITICAL',true,'["dep_mlb_evidence","dep_mlb_tool_events"]'),
('@DepuracionMLB','DEP-P4-03','P4','Claims evidence-bound','Material claims are bound to current-run evidence rather than free narrative.','MAJOR',true,'["dep_mlb_claims","dep_mlb_evidence"]'),
('@DepuracionMLB','DEP-P5-01','P5','F1-F10 progressive order','Phases advance in declared order with F6 conditional, F7-F8 survivor-only, F9 horizontal, F10 delivery validation.','CRITICAL',true,'["dep_mlb_phase_state"]'),
('@DepuracionMLB','DEP-P5-02','P5','Target coverage matches phase contract','F2-F5 all eligible; F6 F5-discriminant; F7-F8 survivors; F9 all eligible plus horizontal audit.','CRITICAL',true,'["dep_mlb_phase_state","dep_mlb_phase_artifacts","dep_mlb_games"]'),
('@DepuracionMLB','DEP-P5-03','P5','Semantic artifact before phase PASS','Every targeted phase PASS has semantic artifact coverage and database-derived phase hash.','CRITICAL',true,'["dep_mlb_phase_state","dep_mlb_phase_artifacts"]'),
('@DepuracionMLB','DEP-P6-01','P6','Kernel does not replace sports reasoning','AI_AGENT owns semantic/causal sports reasoning; Kernel/process auditor enforces process and may not score-vote picks.','CRITICAL',true,'["phase_artifacts","process_audits","manifest"]'),
('@DepuracionMLB','DEP-P6-02','P6','F9 symmetric Red Team and rescue','F9 provides 100% comparative closure, symmetric Red Team and false-negative rescue across eligible games.','CRITICAL',true,'["dep_mlb_phase_artifacts","dep_mlb_game_packets"]'),
('@DepuracionMLB','DEP-P6-03','P6','No packet freeze before F9','Packets freeze only after F9 and with event-attested Drive artifact/readback.','CRITICAL',true,'["dep_mlb_game_packets","dep_mlb_drive_artifacts","dep_mlb_tool_events"]'),
('@DepuracionMLB','DEP-P6-04','P6','Process audit database-derived','Caller/assistant cannot author process-audit PASS; status is derived by DATABASE_CONTROL_V04.','CRITICAL',true,'["dep_mlb_process_audits"]'),
('@DepuracionMLB','DEP-P6-05','P6','Reopen semantics respected','Before F9 selective reopen uses fresh same-run Web evidence; after F9 material delta requires a new clean-room run.','MAJOR',true,'["dep_mlb_reopen_events","dep_mlb_phase_state","dep_mlb_runs"]'),
('@DepuracionMLB','DEP-P7-01','P7','Sports/process states not conflated','UNKNOWN/UNRESOLVED or one bad fact does not automatically reject; one good fact does not auto-promote.','MAJOR',true,'["dep_mlb_phase_artifacts","dep_mlb_game_packets"]'),
('@DepuracionMLB','DEP-P7-02','P7','Candidate class limits and types','Handoff has max 4 primary and 2 potential; all remaining games retain NOT_ADVANCED or explicit disposition.','CRITICAL',true,'["dep_mlb_handoffs","dep_mlb_games"]'),
('@DepuracionMLB','DEP-P8-01','P8','Drive artifacts and hashes reconcile','RUN_DOSSIER, packets and HANDOFF_REPORT referenced by DB exist/read back and hashes/receipts reconcile.','CRITICAL',true,'["dep_mlb_drive_artifacts","dep_mlb_invocation_drive_receipts","dep_mlb_runs"]'),
('@DepuracionMLB','DEP-P8-02','P8','Exclusive report identity preserved','report_drive_file_id/hash belongs exclusively to audited RUN and is not reused silently across runs.','CRITICAL',true,'["dep_mlb_runs","dep_mlb_drive_artifacts"]'),
('@DepuracionMLB','DEP-P9-01','P9','Supabase GitHub Drive authority consistency','Manifest, run metadata, connector registry and canonical Drive authority agree on active identity or mismatch is reported.','CRITICAL',true,'["dep_mlb_runs","dep_mlb_connector_registry","GitHub manifest","Drive mother"]'),
('@DepuracionMLB','DEP-P9-02','P9','Vercel optional truth preserved','Vercel NOT_VISIBLE does not invalidate connected ChatGPT execution and may not be falsely reported deployed.','MAJOR',true,'["dep_mlb_connector_registry"]'),
('@DepuracionMLB','DEP-P10-01','P10','Terminal mutation resistance','After terminal closure attempts to mutate frozen/closed truth are rejected or prevented.','CRITICAL',true,'["dep_mlb_runs","dep_mlb_phase_state","dep_mlb_game_packets"]'),
('@DepuracionMLB','DEP-P10-02','P10','Kernel validation provenance','If 17/17 or controlled E2E validation is cited, verify physical dep_mlb_kernel_tests/run evidence rather than narrative.','MAJOR',true,'["dep_mlb_kernel_tests","dep_mlb_runs"]'),
('@DepuracionMLB','DEP-P11-01','P11','F10 complete delivery package','F10 PASS requires audited packets, verified RUN_DOSSIER, HANDOFF_REPORT, typed candidate payloads, frozen MLB_CHAT_REPORT_STANDARD_R1 and DELIVERY_STATUS COMPLETE.','CRITICAL',true,'["dep_mlb_game_packets","dep_mlb_drive_artifacts","dep_mlb_handoffs","dep_mlb_chat_reports","dep_mlb_phase_state"]'),
('@DepuracionMLB','DEP-P11-02','P11','F10 seals run and invocation','Completed F10 closes/seals run and invocation consistently; incomplete delivery cannot masquerade as completed handoff.','CRITICAL',true,'["dep_mlb_runs","dep_mlb_agent_invocations","dep_mlb_phase_state"]'),
('@DepuracionMLB','DEP-P12-01','P12','Audit verdict derived from physical checks','Auditor verdict reflects all mandatory checks; sports result cannot upgrade or downgrade process verdict.','CRITICAL',true,'["system_audit_runs","system_audit_checks"]');

update public.system_auditor_authority
set migrations_required_through=42,
    metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object(
      'target_menu',jsonb_build_object('1','@NRFiPrensa','2','@NRFImetrica','3','@DepuracionMLB'),
      'depuracion_mlb_adapter','ADAPTER-1.0',
      'depuracion_mlb_authority','DEP-MLB-AGENT-1.2 / DEP-MLB-KERNEL-0.4-AUTONOMOUS-REFACTOR'
    ),
    updated_at=now()
where protocol_id='SYSTEM_AUDITOR_V1';
