-- @investigacionNRFI semantic completeness enforcement 1.1
-- Phase status and game status are derived from physical structured objects.

create or replace function public.investigacion_nrfi_game_semantic_ready(p_daily_run_id text,p_game_pk text)
returns jsonb language plpgsql security definer set search_path=public,extensions as $$
declare g public.investigacion_nrfi_games%rowtype; lineup_count integer; half_count integer; pa_top integer; pa_bottom integer; pitch_count integer; pa_pitch_mismatch integer; starter_context_count integer; family_count integer; seq_window_count integer; press_ok boolean; cohorts_ok boolean; lineup_gap boolean; pitch_gap boolean; f1_ok boolean; f2_ok boolean; f3_ok boolean; f4_ok boolean;
begin
 select * into g from public.investigacion_nrfi_games where daily_run_id=p_daily_run_id and game_pk=p_game_pk; if not found then raise exception 'GAME_NOT_FOUND'; end if;
 select count(*) into lineup_count from public.investigacion_nrfi_lineup_entries where daily_run_id=p_daily_run_id and game_pk=p_game_pk;
 select exists(select 1 from public.investigacion_nrfi_component_coverage where daily_run_id=p_daily_run_id and game_pk=p_game_pk and component='LINEUP_CATCHER' and status='BOUNDED_GAP') into lineup_gap;
 f1_ok := nullif(g.away_team,'') is not null and nullif(g.home_team,'') is not null and g.actual_first_pitch_at is not null and g.first_pitch_verified=true and nullif(g.venue_name,'') is not null and nullif(g.away_starter_id,'') is not null and nullif(g.home_starter_id,'') is not null and g.final_score_away is not null and g.final_score_home is not null and nullif(g.data_era,'') is not null and ((lineup_count>=18 and g.away_catcher_id is not null and g.home_catcher_id is not null) or lineup_gap);
 select count(*) into half_count from public.investigacion_nrfi_half_innings where daily_run_id=p_daily_run_id and game_pk=p_game_pk and inning=1;
 select count(*) into pa_top from public.investigacion_nrfi_plate_appearances where daily_run_id=p_daily_run_id and game_pk=p_game_pk and half='TOP';
 select count(*) into pa_bottom from public.investigacion_nrfi_plate_appearances where daily_run_id=p_daily_run_id and game_pk=p_game_pk and half='BOTTOM';
 select count(*) into pitch_count from public.investigacion_nrfi_pitch_events where daily_run_id=p_daily_run_id and game_pk=p_game_pk;
 select count(*) into pa_pitch_mismatch from public.investigacion_nrfi_plate_appearances pa where pa.daily_run_id=p_daily_run_id and pa.game_pk=p_game_pk and pa.pitch_count>0 and pa.pitch_count<>(select count(*) from public.investigacion_nrfi_pitch_events pe where pe.daily_run_id=pa.daily_run_id and pe.game_pk=pa.game_pk and pe.pa_id=pa.pa_id);
 select exists(select 1 from public.investigacion_nrfi_component_coverage where daily_run_id=p_daily_run_id and game_pk=p_game_pk and component='PITCH_LEVEL' and status='BOUNDED_GAP') into pitch_gap;
 select count(*) into starter_context_count from public.investigacion_nrfi_starter_contexts where daily_run_id=p_daily_run_id and game_pk=p_game_pk;
 f2_ok := exists(select 1 from public.investigacion_nrfi_first_innings where daily_run_id=p_daily_run_id and game_pk=p_game_pk) and half_count=2 and pa_top>=3 and pa_bottom>=3 and starter_context_count>=2 and ((pitch_count>0 and pa_pitch_mismatch=0) or pitch_gap);
 select count(distinct feature_family) into family_count from public.investigacion_nrfi_feature_values where daily_run_id=p_daily_run_id and game_pk=p_game_pk;
 select count(distinct feature_window) into seq_window_count from public.investigacion_nrfi_feature_values where daily_run_id=p_daily_run_id and game_pk=p_game_pk and feature_family='SEQUENCE' and feature_window in ('L3','L5','L10','L15','L20','SEASON','CAREER');
 f3_ok := family_count=9 and seq_window_count=7;
 select exists(select 1 from public.investigacion_nrfi_component_coverage where daily_run_id=p_daily_run_id and game_pk=p_game_pk and component='PRESS_HUMAN_INFORMATION' and status in ('COMPLETE','BOUNDED_GAP')) into press_ok;
 select exists(select 1 from public.investigacion_nrfi_component_coverage where daily_run_id=p_daily_run_id and game_pk=p_game_pk and component='COHORTS' and status in ('COMPLETE','BOUNDED_GAP','NOT_APPLICABLE')) into cohorts_ok;
 f4_ok := press_ok and cohorts_ok and half_count=2 and not exists(select 1 from public.investigacion_nrfi_half_innings where daily_run_id=p_daily_run_id and game_pk=p_game_pk and (nullif(primary_path,'') is null or jsonb_array_length(exact_event_sequence)=0));
 return jsonb_build_object('game_pk',p_game_pk,'f1',f1_ok,'f2',f2_ok,'f3',f3_ok,'f4',f4_ok,'lineup_count',lineup_count,'half_count',half_count,'pa_top',pa_top,'pa_bottom',pa_bottom,'pitch_count',pitch_count,'pa_pitch_mismatch',pa_pitch_mismatch,'starter_context_count',starter_context_count,'feature_family_count',family_count,'sequence_window_count',seq_window_count,'press_coverage',press_ok,'cohort_coverage',cohorts_ok,'lineup_bounded_gap',lineup_gap,'pitch_bounded_gap',pitch_gap);
end $$;

create or replace function public.investigacion_nrfi_semantic_completeness(p_daily_run_id text)
returns jsonb language plpgsql security definer set search_path=public,extensions as $$
declare r public.investigacion_nrfi_runs%rowtype; target_count integer; processed_count integer; f1_ready integer:=0; f2_ready integer:=0; f3_ready integer:=0; f4_ready integer:=0; packet_ok boolean:=false; report_ok boolean:=false; min_report_chars integer:=0; rec record; s jsonb; f1_ok boolean; f2_ok boolean; f3_ok boolean; f4_ok boolean; f5_ok boolean;
begin
 select * into r from public.investigacion_nrfi_runs where daily_run_id=p_daily_run_id; if not found then raise exception 'DAILY_RUN_NOT_FOUND'; end if;
 select count(*) into target_count from public.investigacion_nrfi_games where daily_run_id=p_daily_run_id and research_status<>'EXCLUDED';
 select count(*) into processed_count from public.investigacion_nrfi_games where daily_run_id=p_daily_run_id and research_status='PROCESSED';
 for rec in select game_pk from public.investigacion_nrfi_games where daily_run_id=p_daily_run_id and research_status<>'EXCLUDED' loop s:=public.investigacion_nrfi_game_semantic_ready(p_daily_run_id,rec.game_pk); if coalesce((s->>'f1')::boolean,false) then f1_ready:=f1_ready+1; end if; if coalesce((s->>'f2')::boolean,false) then f2_ready:=f2_ready+1; end if; if coalesce((s->>'f3')::boolean,false) then f3_ready:=f3_ready+1; end if; if coalesce((s->>'f4')::boolean,false) then f4_ready:=f4_ready+1; end if; end loop;
 f1_ok:=target_count>0 and f1_ready=target_count; f2_ok:=target_count>0 and f2_ready=target_count; f3_ok:=target_count>0 and f3_ready=target_count; f4_ok:=target_count>0 and f4_ready=target_count;
 select exists(select 1 from public.investigacion_nrfi_evidence_packets p where p.daily_run_id=p_daily_run_id and p.future_game_count=0 and p.postgame_leak_count=0 and p.packet_payload ?& array['PITCHER_HISTORY','TEAM_HISTORY','TOP_ORDER_HISTORY','PROCESS_HISTORY','EVENT_PATHS','CONTEXT','PRESS_HISTORY_PREGAME','POSTGAME_EXPLANATORY_SEPARATE','SAMPLE_RELIABILITY','DATA_COVERAGE','SOURCE_LINEAGE','UNCERTAINTY','COMPARABLE_COHORTS']) into packet_ok; f5_ok:=packet_ok;
 min_report_chars:=greatest(12000,target_count*1800);
 select exists(select 1 from public.investigacion_nrfi_drive_appends d where d.daily_run_id=p_daily_run_id and d.verified=true and d.report_contract_verified=true and d.game_block_count=target_count and d.phase_section_count>=5 and d.daily_block_character_count>=min_report_chars and d.required_section_markers @> '{"EXECUTION_SUMMARY":true,"F1":true,"F2":true,"F3":true,"F4":true,"F5":true,"DAILY_CLOSURE":true,"GAME_BLOCKS":true}'::jsonb) into report_ok;
 return jsonb_build_object('target_games',target_count,'processed_games',processed_count,'f1_ready_games',f1_ready,'f2_ready_games',f2_ready,'f3_ready_games',f3_ready,'f4_ready_games',f4_ready,'f1_pass',f1_ok,'f2_pass',f2_ok,'f3_pass',f3_ok,'f4_pass',f4_ok,'f5_pass',f5_ok,'report_contract_pass',report_ok,'minimum_daily_block_characters',min_report_chars,'all_games_processed',processed_count=target_count,'pass',(target_count>0 and processed_count=target_count and f1_ok and f2_ok and f3_ok and f4_ok and f5_ok and report_ok));
end $$;

create or replace function public.investigacion_nrfi_guard_game_processed() returns trigger language plpgsql set search_path=public,extensions as $$ declare s jsonb; begin if new.research_status='PROCESSED' and old.research_status is distinct from 'PROCESSED' then s:=public.investigacion_nrfi_game_semantic_ready(new.daily_run_id,new.game_pk); if not (coalesce((s->>'f1')::boolean,false) and coalesce((s->>'f2')::boolean,false) and coalesce((s->>'f3')::boolean,false) and coalesce((s->>'f4')::boolean,false)) then raise exception 'GAME_SEMANTIC_COMPLETENESS_REQUIRED:%',s::text; end if; end if; return new; end $$;
drop trigger if exists investigacion_nrfi_game_semantic_ready_trg on public.investigacion_nrfi_games;
create trigger investigacion_nrfi_game_semantic_ready_trg before update of research_status on public.investigacion_nrfi_games for each row execute function public.investigacion_nrfi_guard_game_processed();

create or replace function public.investigacion_nrfi_guard_phase_state() returns trigger language plpgsql set search_path=public,extensions as $$
declare phase_rank integer; prior_missing integer; required_keys text[]:=array['PHASE_ID','START_AS_OF','END_AS_OF','INPUT_OBJECTS','OPERATIONS_PERFORMED','OUTPUT_OBJECTS','SOURCES_OR_EVIDENCE','AUDITOR_RESULT','NEXT_PHASE']; expected_count integer; accounted_count integer; ledger_count integer; semantic jsonb;
begin
 phase_rank:=case new.phase_id when 'F1_FORENSIC_CAPTURE' then 1 when 'F2_DEEP_RECONSTRUCTION' then 2 when 'F3_FEATURE_FACTORY' then 3 when 'F4_HISTORICAL_PRESS_RELIABILITY' then 4 when 'F5_QUERYABLE_INTELLIGENCE' then 5 else 99 end;
 if public.investigacion_nrfi_payload_has_forbidden_keys(new.payload) then raise exception 'FORBIDDEN_PICK_OR_MARKET_OUTPUT'; end if;
 if new.status='COMPLETE' then
  if not (new.receipt ?& required_keys) then raise exception 'PHASE_EXECUTION_RECEIPT_INCOMPLETE'; end if;
  if coalesce(new.receipt->>'PHASE_ID','')<>new.phase_id then raise exception 'RECEIPT_PHASE_ID_MISMATCH'; end if;
  semantic:=public.investigacion_nrfi_semantic_completeness(new.daily_run_id);
  if new.phase_id='F1_FORENSIC_CAPTURE' then expected_count:=(new.payload#>>'{universe,expected_finalized_game_count}')::integer; accounted_count:=(new.payload#>>'{universe,accounted_game_count}')::integer; select count(*) into ledger_count from public.investigacion_nrfi_games where daily_run_id=new.daily_run_id; if expected_count<>accounted_count or expected_count<>ledger_count then raise exception 'F1_UNIVERSE_NOT_FULLY_BOUND'; end if; if not coalesce((semantic->>'f1_pass')::boolean,false) then raise exception 'F1_PHYSICAL_SEMANTIC_OBJECTS_INCOMPLETE:%',semantic::text; end if;
  elsif new.phase_id='F2_DEEP_RECONSTRUCTION' and not coalesce((semantic->>'f2_pass')::boolean,false) then raise exception 'F2_PITCH_PA_HALF_FIRST_INNING_CONTEXT_INCOMPLETE:%',semantic::text;
  elsif new.phase_id='F3_FEATURE_FACTORY' and not coalesce((semantic->>'f3_pass')::boolean,false) then raise exception 'F3_REQUIRED_FEATURE_FAMILIES_OR_WINDOWS_INCOMPLETE:%',semantic::text;
  elsif new.phase_id='F4_HISTORICAL_PRESS_RELIABILITY' and not coalesce((semantic->>'f4_pass')::boolean,false) then raise exception 'F4_PRESS_RELIABILITY_MECHANISM_COHORT_COVERAGE_INCOMPLETE:%',semantic::text;
  elsif new.phase_id='F5_QUERYABLE_INTELLIGENCE' and not coalesce((semantic->>'f5_pass')::boolean,false) then raise exception 'F5_EVIDENCE_PACKET_INCOMPLETE:%',semantic::text; end if;
 end if;
 if phase_rank>1 then select count(*) into prior_missing from (values(1,'F1_FORENSIC_CAPTURE'),(2,'F2_DEEP_RECONSTRUCTION'),(3,'F3_FEATURE_FACTORY'),(4,'F4_HISTORICAL_PRESS_RELIABILITY'),(5,'F5_QUERYABLE_INTELLIGENCE')) p(rank,pid) where p.rank<phase_rank and not exists(select 1 from public.investigacion_nrfi_phase_state s where s.daily_run_id=new.daily_run_id and s.phase_id=p.pid and s.status='COMPLETE'); if prior_missing>0 then raise exception 'PREREQUISITES_INCOMPLETE'; end if; end if;
 return new;
end $$;

create or replace function public.investigacion_nrfi_derive_audit(p_daily_run_id text) returns public.investigacion_nrfi_audits language plpgsql security definer set search_path=public,extensions as $$
declare r public.investigacion_nrfi_runs%rowtype; out_row public.investigacion_nrfi_audits%rowtype; completed text[]; missing text[]; temporal_ok boolean; trace_ok boolean; drive_ok boolean; universe_ok boolean; ledger_expected integer; ledger_processed integer; ledger_excluded integer; ledger_pending integer; semantic jsonb; semantic_ok boolean; report_ok boolean;
begin
 perform public.investigacion_nrfi_sync_run_accounting(p_daily_run_id); select * into r from public.investigacion_nrfi_runs where daily_run_id=p_daily_run_id; if not found then raise exception 'DAILY_RUN_NOT_FOUND'; end if;
 select count(*),count(*) filter(where research_status='PROCESSED'),count(*) filter(where research_status='EXCLUDED'),count(*) filter(where research_status='PENDING') into ledger_expected,ledger_processed,ledger_excluded,ledger_pending from public.investigacion_nrfi_games where daily_run_id=p_daily_run_id;
 select coalesce(array_agg(phase_id order by phase_id),'{}'::text[]) into completed from public.investigacion_nrfi_phase_state where daily_run_id=p_daily_run_id and status='COMPLETE';
 select coalesce(array_agg(pid),'{}'::text[]) into missing from unnest(array['F1_FORENSIC_CAPTURE','F2_DEEP_RECONSTRUCTION','F3_FEATURE_FACTORY','F4_HISTORICAL_PRESS_RELIABILITY','F5_QUERYABLE_INTELLIGENCE']) pid where not(pid=any(completed));
 universe_ok:=ledger_pending=0 and ledger_expected=ledger_processed+ledger_excluded and r.expected_finalized_count=ledger_expected and r.processed_count=ledger_processed and r.excluded_count=ledger_excluded;
 select not exists(select 1 from public.investigacion_nrfi_evidence e where e.daily_run_id=p_daily_run_id and e.temporal_lane='PREGAME_EVIDENCE' and (e.available_at is null or e.first_pitch_at is null or e.available_at>=e.first_pitch_at)) into temporal_ok;
 select case when ledger_expected=0 then true else exists(select 1 from public.investigacion_nrfi_evidence e where e.daily_run_id=p_daily_run_id) and not exists(select 1 from public.investigacion_nrfi_evidence e left join public.investigacion_nrfi_tool_events t on t.event_id=e.tool_event_id left join public.investigacion_nrfi_source_families f on f.source_family_id=e.source_family_id where e.daily_run_id=p_daily_run_id and (t.event_id is null or f.source_family_id is null)) end into trace_ok;
 select exists(select 1 from public.investigacion_nrfi_drive_appends d where d.daily_run_id=p_daily_run_id and d.verified=true) into drive_ok;
 semantic:=public.investigacion_nrfi_semantic_completeness(p_daily_run_id); semantic_ok:=coalesce((semantic->>'pass')::boolean,false); report_ok:=coalesce((semantic->>'report_contract_pass')::boolean,false);
 insert into public.investigacion_nrfi_audits(daily_run_id,phases_expected,phases_executed,mandatory_phases_not_run,universe_accounting_pass,temporal_integrity_pass,evidence_trace_pass,drive_append_pass,audit_status,details,derived_at,semantic_completeness_pass,f1_semantic_pass,f2_semantic_pass,f3_semantic_pass,f4_semantic_pass,f5_semantic_pass,report_contract_pass,semantic_details)
 values(p_daily_run_id,5,cardinality(completed),missing,universe_ok,temporal_ok,trace_ok,drive_ok,case when cardinality(missing)=0 and universe_ok and temporal_ok and trace_ok and drive_ok and semantic_ok then 'PASS' else 'FAIL' end,jsonb_build_object('ledger_expected',ledger_expected,'ledger_processed',ledger_processed,'ledger_excluded',ledger_excluded,'ledger_pending',ledger_pending,'agent_id','@investigacionNRFI'),now(),semantic_ok,coalesce((semantic->>'f1_pass')::boolean,false),coalesce((semantic->>'f2_pass')::boolean,false),coalesce((semantic->>'f3_pass')::boolean,false),coalesce((semantic->>'f4_pass')::boolean,false),coalesce((semantic->>'f5_pass')::boolean,false),report_ok,semantic)
 on conflict(daily_run_id) do update set phases_executed=excluded.phases_executed,mandatory_phases_not_run=excluded.mandatory_phases_not_run,universe_accounting_pass=excluded.universe_accounting_pass,temporal_integrity_pass=excluded.temporal_integrity_pass,evidence_trace_pass=excluded.evidence_trace_pass,drive_append_pass=excluded.drive_append_pass,audit_status=excluded.audit_status,details=excluded.details,derived_at=excluded.derived_at,semantic_completeness_pass=excluded.semantic_completeness_pass,f1_semantic_pass=excluded.f1_semantic_pass,f2_semantic_pass=excluded.f2_semantic_pass,f3_semantic_pass=excluded.f3_semantic_pass,f4_semantic_pass=excluded.f4_semantic_pass,f5_semantic_pass=excluded.f5_semantic_pass,report_contract_pass=excluded.report_contract_pass,semantic_details=excluded.semantic_details returning * into out_row; return out_row;
end $$;

revoke all on function public.investigacion_nrfi_game_semantic_ready(text,text),public.investigacion_nrfi_semantic_completeness(text),public.investigacion_nrfi_guard_game_processed(),public.investigacion_nrfi_guard_phase_state(),public.investigacion_nrfi_derive_audit(text) from public,anon,authenticated;
grant execute on function public.investigacion_nrfi_game_semantic_ready(text,text),public.investigacion_nrfi_semantic_completeness(text),public.investigacion_nrfi_derive_audit(text) to service_role;
